### ISSUE TITLE
Error: Unsupported attribute

### ISSUE THREAD

**Issue by eliesadjal** [kumarvna/terraform-azurerm-vnet#4]
I copied pasted the exact code that I found on the terraform website 
at https://registry.terraform.io/modules/kumarvna/vnet/azurerm/latest/examples/complete and when I run Terraform plan, I get this error : 

Error: Unsupported attribute
│ 
│   on .terraform/modules/vnet/output.tf line 38, in output "subnet_address_prefixes":
│   38:   value       = flatten(concat([for s in azurerm_subnet.snet : s.address_prefix], [var.gateway_subnet_address_prefix != null ? azurerm_subnet.gw_snet.0.address_prefixes : null], [var.firewall_subnet_address_prefix != null ? azurerm_subnet.fw-snet.0.address_prefixes : null]))
│ 
│ This object does not have an attribute named "address_prefix".

If someone could explain to me why it would be great.
Thanks.

**Comment by archmangler** [comment]
It means the module outputs is trying to address an attribute that doesn't exist in the subnet resource:

`../../modules/terraform-azurerm-vnet/output.tf`

```
output "subnet_address_prefixes" {
  description = "List of address prefix for subnets"
value       = flatten(concat([for s in azurerm_subnet.snet : s.address_prefix], [var.gateway_subnet_address_prefix != null ? azurerm_subnet.gw_snet.0.address_prefixes : null], [var.firewall_subnet_address_prefix != null ? azurerm_subnet.fw-snet.0.address_prefixes : null]))
}
```

Looking at the main.tf for the relevant resource, there is a address_prefixes resource ... not sure if that's  what the author intended. You could try this:

```
output "subnet_address_prefixes" {
   description = "List of address prefix for subnets"
   value       = flatten(concat([for s in azurerm_subnet.snet : s.address_prefixes], [var.gateway_subnet_address_prefix != null ? azurerm_subnet.gw_snet.0.address_prefixes : null], [var.firewall_subnet_address_prefix != null ? azurerm_subnet.fw-snet.0.address_prefixes : null]))
}
```

**Comment by kumarvna** [comment]
This is fixed now, please use the latest release.
